server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;
	root /var/www/html
	server_name cobussie.42.fr;
	index index.php index.html index.htm;
	location / {
		try_files $uri $uri/ =404;
	}
	location ~ \.php$ {
		# 1. On sépare l'URL pour la sécurité et le bon routage de WordPress
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		
		# 2. L'envoi vers ton conteneur PHP (Ce que tu avais bien mis !)
		fastcgi_pass wordpress:9000; 
		
		# 3. Le script par défaut
		fastcgi_index index.php;
		
		# 4. On inclut les paramètres de base (ce fichier 'fastcgi_params' existe partout, contrairement aux 'snippets')
		include fastcgi_params;
		
		# 5. LA LIGNE CRUCIALE : on donne à PHP le chemin absolu du fichier à exécuter
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		
		# 6. Utile pour faire fonctionner correctement les permaliens de WordPress
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}
